# Generated by Django 2.2.16 on 2021-08-12 09:53

import django.db.models.deletion
from django.db import migrations, models

import content.validators


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='content.Category'),
        ),
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(related_name='titles', to='content.Genre'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(default=1, validators=[content.validators.year_validator], verbose_name='Year'),
            preserve_default=False,
        ),
    ]
