# Generated by Django 2.2.16 on 2021-08-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210812_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
